FROM node:22-alpine AS build

ARG ALPINE_MIRROR=mirrors.aliyun.com
RUN sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_MIRROR}/g" /etc/apk/repositories \
    && apk add --no-cache gcc musl-dev make tcl
ADD --checksum=sha256:99c578c9326b12374a64dedae88a63d17557b5d2b0ac65122be67cb3fa2703da \
    https://codeload.github.com/sqlite/sqlite/tar.gz/refs/tags/version-3.46.1 /tmp/sqlite.tar.gz
WORKDIR /build
RUN tar -xzf /tmp/sqlite.tar.gz --strip-components=1 \
    && ./configure --disable-readline \
    && make -j1 sqlite3.c shell.c \
    && cc -static -Os -DSQLITE_THREADSAFE=1 -DSQLITE_OMIT_LOAD_EXTENSION \
       -o /usr/bin/sqlite3 shell.c sqlite3.c -lm -lpthread \
    && /usr/bin/sqlite3 --version

FROM scratch
COPY --from=build /usr/bin/sqlite3 /usr/bin/sqlite3
USER 0:0
ENTRYPOINT ["/usr/bin/sqlite3"]
