// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.3
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EnrollService_Enroll_FullMethodName = "/alinksec.v1.EnrollService/Enroll"
)

// EnrollServiceClient is the client API for EnrollService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollServiceClient interface {
	// 首次安装调用；成功后 Agent 持久化证书，改走 mTLS 主通道
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type enrollServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollServiceClient(cc grpc.ClientConnInterface) EnrollServiceClient {
	return &enrollServiceClient{cc}
}

func (c *enrollServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EnrollService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollServiceServer is the server API for EnrollService service.
// All implementations must embed UnimplementedEnrollServiceServer
// for forward compatibility
type EnrollServiceServer interface {
	// 首次安装调用；成功后 Agent 持久化证书，改走 mTLS 主通道
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedEnrollServiceServer()
}

// UnimplementedEnrollServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnrollServiceServer struct {
}

func (UnimplementedEnrollServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollServiceServer) mustEmbedUnimplementedEnrollServiceServer() {}

// UnsafeEnrollServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollServiceServer will
// result in compilation errors.
type UnsafeEnrollServiceServer interface {
	mustEmbedUnimplementedEnrollServiceServer()
}

func RegisterEnrollServiceServer(s grpc.ServiceRegistrar, srv EnrollServiceServer) {
	s.RegisterService(&EnrollService_ServiceDesc, srv)
}

func _EnrollService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollService_ServiceDesc is the grpc.ServiceDesc for EnrollService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alinksec.v1.EnrollService",
	HandlerType: (*EnrollServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _EnrollService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

const (
	AgentChannel_Channel_FullMethodName = "/alinksec.v1.AgentChannel/Channel"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentChannelClient interface {
	// Agent 发起；上行 stream Report，下行 stream Command
	Channel(ctx context.Context, opts ...grpc.CallOption) (AgentChannel_ChannelClient, error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Channel(ctx context.Context, opts ...grpc.CallOption) (AgentChannel_ChannelClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &agentChannelChannelClient{ClientStream: stream}
	return x, nil
}

type AgentChannel_ChannelClient interface {
	Send(*Report) error
	Recv() (*Command, error)
	grpc.ClientStream
}

type agentChannelChannelClient struct {
	grpc.ClientStream
}

func (x *agentChannelChannelClient) Send(m *Report) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentChannelChannelClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility
type AgentChannelServer interface {
	// Agent 发起；上行 stream Report，下行 stream Command
	Channel(AgentChannel_ChannelServer) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have forward compatible implementations.
type UnimplementedAgentChannelServer struct {
}

func (UnimplementedAgentChannelServer) Channel(AgentChannel_ChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Channel(&agentChannelChannelServer{ServerStream: stream})
}

type AgentChannel_ChannelServer interface {
	Send(*Command) error
	Recv() (*Report, error)
	grpc.ServerStream
}

type agentChannelChannelServer struct {
	grpc.ServerStream
}

func (x *agentChannelChannelServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentChannelChannelServer) Recv() (*Report, error) {
	m := new(Report)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alinksec.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _AgentChannel_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
